name: Java CI with Maven and Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Install local dependencies
        run: mvn install:install-file -Dfile=IlpDataObjects.jar -DgroupId=ilp -DartifactId=ilp -Dversion=1.0 -Dpackaging=jar

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report

      # If you want to upload the report to a service like Codecov or Coveralls
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
